jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        node-version: [18, 20, 22]
        attempt: [1, 2, 3, 4, 5]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies using pnpm
        run: pnpm install

      - name: Install Dependencies (Ubuntu)
        if: runner.os == 'Linux'
        run: |
          sudo apt update
          sudo apt install -y default-jre firefox xvfb

      - name: Install Dependencies (macOS)
        if: runner.os == 'macOS'
        run: |
          brew install openjdk firefox
          echo 'export PATH="/opt/homebrew/opt/openjdk/bin:$PATH"' >> $HOME/.zshrc
          source $HOME/.zshrc

      - name: Install Dependencies (Windows)
        if: runner.os == 'Windows'
        run: |
          choco install openjdk firefox
        shell: powershell

      - name: Run Tests (Headless Mode)
        run: |
          echo "Run attempt: ${{ matrix.attempt }}"
          pnpm test -- --browsers ChromeHeadlessCI,FirefoxHeadlessCI
